#!/usr/bin/perl
# feed me the 'testday' TSV format, with at least these columns:
# Class, No., Member #, Test Day Segment

use Text::CSV;

my @Days = qw(Thu Fri Sat Sun Mon);
my %Days = map(($Days[$_] => 1+$_), 0..$#Days);

my $IN = Text::CSV->new( {
    sep_char => "\t", quote_char => undef, escape_char => undef, binary => 1,
  });
$IN->column_names($IN->getline(\*STDIN));

while ($hr = $IN->getline_hr(\*STDIN)) {
  my $class = $$hr{'Class'};
  $class =~ s/^(bs|bspec|b-spec)$/B-Spec/i;

  $key = join('_', $class, $$hr{'Member #'});
  $day = substr($$hr{'Test Day Segment'}, 0, 3);
  #$Entries{$key}{$day} = $Days{$day} || 99;
  $Entries{$key}{$day} = $$hr{'No.'};
}

my $OUT = Text::CSV->new( {
    quote_space => 1, binary => 1, eol => "\r\n",
  });
$OUT->print(\*STDOUT, [qw[Cls_Member Days], @Days]);
foreach my $entry (sort keys %Entries) {
  $OUT->print(\*STDOUT, [
      $entry,
      join(' ', sort {
        $Days{$a} <=> $Days{$b} || $a cmp $b
        } keys %{$Entries{$entry}}),
      map($Entries{$entry}{$_} // '', @Days)
    ]);
}
